# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialApp
  pod 'Alamofire', '~> 5.4'
  pod 'RealmSwift', '~> 10.3'
  pod 'SwiftKeychainWrapper', '~> 4.0'
  pod 'Kingfisher', '~> 5.15'
  pod 'FirebaseCore', '~> 7.3'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'PromiseKit', '~> 6.13'
  
end
